clusters:
  - name: Test # Cluster Name
    username: mmsuper # Default username used to access logical servers databases
    password: mediation
    logical-servers:
      - name: Server5
        ip: 10.135.5.81
        username: mmsuper
        passwod: thule
        port: 5432
  - name: ryd2
    username: mmsuper
    password: mediation
    logical-servers:
      - name: Server1
        ip: 10.135.3.125
  - name: dev
    username: mmsuper
    password: mediation
    logical-servers:
      - name: Server11
        ip: localhost
        port: 5432
        username: mmsuper
        password: mediation
        database: fm_db_Server11

configurations:
  - name: UAT_Test
    collectors: ["INPUT", "Output"]
    distributors: ["BI", "RA"]
    assigned-logical-server:
      name: Server1
      cluster: ryd2
  - name: 4GLTE
    assigned-logical-server:
      name: Server11
      cluster: dev